language: python
sudo: required
group: edge
env:
  - TEST=python TEST_MIGRATIONS=true REUSE_DB=true  # can't drop the citus DB since it's the postgres database
before_install:
  # get newer version of docker-compose for variable substitution in compose files
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.26.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv -v docker-compose /usr/local/bin/
install:
  - .travis/setup_commcare.sh
before_script:
  - docker version
  - docker-compose version
  - cd $HOME/commcare
script:
  - scripts/docker test extensions/icds --noinput --stop --verbosity=2 --divide-depth=1 --with-timing --threshold=10 --max-test-time=29
after_success:
  # create symlink so artifacts are available
  - sudo ln -s $(pwd) /mnt/commcare-hq-ro
services:
  - docker
