# Generated by Django 2.2.13 on 2020-08-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icds', '0008_auto_20200823_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultentry',
            name='form_id',
            field=models.CharField(db_index=True, default=None, max_length=255),
        ),
    ]
