# Generated by Django 1.11.16 on 2018-10-04 21:18
from corehq.sql_db.operations import RawSQLMigration
from django.db import migrations, models

from custom.icds_reports.const import SQL_TEMPLATES_ROOT

migrator = RawSQLMigration((SQL_TEMPLATES_ROOT, 'database_views'))


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0154_child_health_state')
    ]

    operations = [
        migrations.RunSQL(
            "ALTER table icds_dashboard_ccs_record_delivery_forms ADD COLUMN num_children_del SMALLINT",
            state_operations=[
                migrations.AddField(
                    model_name='aggregateccsrecorddeliveryforms',
                    name='num_children_del',
                    field=models.PositiveSmallIntegerField(help_text='Number of children born', null=True)
                )
            ]
        ),
        migrations.RunSQL(
            "ALTER table icds_dashboard_ccs_record_delivery_forms ADD COLUMN still_live_birth SMALLINT",
            state_operations=[
                migrations.AddField(
                    model_name='aggregateccsrecorddeliveryforms',
                    name='still_live_birth',
                    field=models.PositiveSmallIntegerField(help_text='Number of children alive', null=True)
                )
            ]
        ),
        migrations.RunSQL("ALTER table ccs_record_monthly ADD COLUMN husband_name text"),
        migrations.RunSQL("ALTER table ccs_record_monthly ADD COLUMN lmp DATE"),
        migrations.RunSQL("ALTER table ccs_record_monthly ADD COLUMN migration_status SMALLINT"),
        migrations.RunSQL("ALTER table ccs_record_monthly ADD COLUMN where_born SMALLINT"),
        migrations.RunSQL("ALTER table ccs_record_monthly ADD COLUMN num_children_del SMALLINT"),
        migrations.RunSQL("ALTER table ccs_record_monthly ADD COLUMN still_live_birth SMALLINT")
    ]
