# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-17 09:26
from __future__ import unicode_literals


from __future__ import unicode_literals

from django.db import migrations

from custom.icds_reports.utils.migrations import get_view_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0200_update_chm_ccs_view'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN total_pse_days_attended smallint"),
    ]
