# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-17 09:26
from __future__ import unicode_literals


from __future__ import unicode_literals

from django.db import migrations

from custom.icds_reports.utils.migrations import get_view_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0201_add_new_column_agg_child'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN pse_attended_16_days_sc integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN pse_attended_16_days_st integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN pse_attended_16_days_other integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN pse_attended_16_days_disabled integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN pse_attended_16_days_minority integer"),

    ]
