# -*- coding: utf-8 -*-
# Generated by Django 1.11.28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0201_auto_20200817_1631'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE child_health_monthly ADD COLUMN fully_immun_before_month_end smallint'),
        migrations.RunSQL('ALTER TABLE agg_child_health ADD COLUMN fully_immun_before_month_end integer'),
        migrations.RunSQL('ALTER TABLE agg_child_health ADD COLUMN fully_immunized_eligible_in_month integer'),
    ]
