# -*- coding: utf-8 -*-
# Generated by Django 1.11.28
from __future__ import unicode_literals


from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0201_auto_20200817_1631'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE ccs_record_monthly ADD COLUMN female_death_type text"),
        migrations.RunSQL("ALTER TABLE agg_ccs_record ADD COLUMN death_during_preg integer"),
        migrations.RunSQL("ALTER TABLE agg_ccs_record ADD COLUMN death_during_delivery integer"),
        migrations.RunSQL("ALTER TABLE agg_ccs_record ADD COLUMN death_pnc integer"),
        migrations.RunSQL("ALTER TABLE child_health_monthly ADD COLUMN live_birth smallint"),
        migrations.RunSQL("ALTER TABLE child_health_monthly ADD COLUMN still_birth smallint"),
        migrations.RunSQL("ALTER TABLE child_health_monthly ADD COLUMN weighed_within_3_days smallint"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN weighed_within_3_days integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN live_birth integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN still_birth integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN deaths integer"),
    ]
