# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-17 09:26
from __future__ import unicode_literals


from __future__ import unicode_literals

from django.db import migrations

from custom.icds_reports.utils.migrations import get_view_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0202_add_new_column_agg_child'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN thr_0_days_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN thr_1_days_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN thr_25_days_sc_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN thr_25_days_st_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN thr_25_days_other_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN thr_25_days_disabled_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN thr_25_days_minority_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN total_thr_resident integer"),

        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN lunch_0_days_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN lunch_1_days_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN lunch_25_days_sc_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN lunch_25_days_st_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN lunch_25_days_other_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN lunch_25_days_disabled_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN lunch_25_days_minority_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN total_lunch_resident integer"),

        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN thr_1_days_migrant integer"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN lunch_1_days_migrant integer"),

        migrations.RunSQL("ALTER TABLE agg_ccs_record ADD COLUMN thr_0_days_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_ccs_record ADD COLUMN thr_1_days_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_ccs_record ADD COLUMN thr_25_days_sc_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_ccs_record ADD COLUMN thr_25_days_st_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_ccs_record ADD COLUMN thr_25_days_other_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_ccs_record ADD COLUMN thr_25_days_disabled_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_ccs_record ADD COLUMN thr_25_days_minority_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_ccs_record ADD COLUMN total_thr_resident integer"),
        migrations.RunSQL("ALTER TABLE agg_ccs_record ADD COLUMN thr_1_days_migrant integer"),


    ]
