# Generated by Django 2.2.13 on 2020-08-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0201_auto_20200818_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggmprawc',
            name='delivery_death_permanent_resident',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggmprawc',
            name='delivery_death_temp_resident',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggmprawc',
            name='mother_death_permanent_resident',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggmprawc',
            name='mother_death_temp_resident',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggmprawc',
            name='pnc_death_permanent_resident',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggmprawc',
            name='pnc_death_temp_resident',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggmprawc',
            name='pregnancy_death_permanent_resident',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggmprawc',
            name='pregnancy_death_temp_resident',
            field=models.IntegerField(null=True),
        ),
        migrations.RunSQL("ALTER TABLE child_health_monthly ADD COLUMN birth_status_in_month TEXT"),
        migrations.RunSQL("ALTER TABLE child_health_monthly ADD COLUMN weighed_within_3_days smallint"),
        migrations.RunSQL("ALTER TABLE child_health_monthly ADD COLUMN mother_resident_status TEXT"),
        # migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN live_birth_permanent_resident INTEGER"),
        # migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN live_birth_temp_resident INTEGER"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN still_birth_permanent_resident INTEGER"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN still_birth_temp_resident INTEGER"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN weighed_in_3_days_permanent_resident INTEGER"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN weighed_in_3_days_temp_resident INTEGER"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN neonatal_deaths_permanent_resident INTEGER"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN neonatal_deaths_temp_resident INTEGER"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN post_neonatal_deaths_permanent_resident INTEGER"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN post_neonatal_deaths_temp_resident INTEGER"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN total_deaths_permanent_resident INTEGER"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN total_deaths_temp_resident INTEGER"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN lbw_permanent_resident INTEGER"),
        migrations.RunSQL("ALTER TABLE agg_child_health ADD COLUMN lbw_temp_resident INTEGER"),

    ]
