# Generated by Django 2.2.13 on 2020-08-24 17:41

from django.db import migrations, models

from custom.icds_reports.utils.migrations import get_view_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0202_agg_daily_thr_form_with_images'),
    ]

    operations = get_view_migrations()
