# Generated by Django 2.2.13 on 2020-08-14 08:13

import custom.icds_reports.models.aggregate
from django.db import migrations, models

from custom.icds_reports.const import AGG_DAILY_CCS_RECORD_THR_TABLE, AGG_DAILY_CHILD_HEALTH_THR_TABLE
from custom.icds_reports.utils.migrations import get_view_migrations, get_composite_primary_key_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0203_auto_20200906_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateDailyCcsRecordTHRForms',
            fields=[
                ('doc_id', models.TextField()),
                ('state_id', models.TextField()),
                ('supervisor_id', models.TextField(null=True)),
                ('month', models.DateField(help_text='Will always be YYYY-MM-01')),
                ('case_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('latest_time_end_processed', models.DateTimeField(help_text='The latest form.meta.timeEnd that has been processed for this case')),
                ('photo_thr_packets_distributed', models.TextField(help_text='Photo taken during thr distribution', null=True)),
            ],
            options={
                'db_table': 'icds_dashboard_daily_ccs_record_thr_forms',
            },
            bases=(models.Model, custom.icds_reports.models.aggregate.AggregateMixin),
        ),
        migrations.AlterUniqueTogether(
            name='aggregatedailyccsrecordthrforms',
            unique_together=set([('month', 'supervisor_id', 'case_id', 'latest_time_end_processed')]),
        ),
        migrations.CreateModel(
            name='AggregateDailyChildHealthTHRForms',
            fields=[
                ('doc_id', models.TextField()),
                ('state_id', models.TextField()),
                ('supervisor_id', models.TextField(null=True)),
                ('month', models.DateField(help_text='Will always be YYYY-MM-01')),
                ('case_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('latest_time_end_processed', models.DateTimeField(help_text='The latest form.meta.timeEnd that has been processed for this case')),
                ('photo_thr_packets_distributed', models.TextField(help_text='Photo taken during thr distribution', null=True)),
            ],
            options={
                'db_table': 'icds_dashboard_daily_child_health_thr_forms',
            },
            bases=(models.Model, custom.icds_reports.models.aggregate.AggregateMixin),
        ),
        migrations.AlterUniqueTogether(
            name='aggregatedailychildhealththrforms',
            unique_together=set([('month', 'supervisor_id', 'case_id', 'latest_time_end_processed')]),
        ),
    ]
    operations.extend(get_composite_primary_key_migrations(['aggregatedailyccsrecordthrforms']))
    operations.extend(get_composite_primary_key_migrations(['aggregatedailychildhealththrforms']))

    operations += [
        migrations.RunSQL(f"SELECT create_distributed_table('{AGG_DAILY_CCS_RECORD_THR_TABLE}', 'supervisor_id')"),
        migrations.RunSQL(f"SELECT create_distributed_table('{AGG_DAILY_CHILD_HEALTH_THR_TABLE}', 'supervisor_id')"),
    ]

    operations.extend(get_view_migrations())

