# Generated by Django 2.2.13 on 2020-08-18 10:55

import custom.icds_reports.models.aggregate
from django.db import migrations, models
from custom.icds_reports.utils.migrations import (
    get_composite_primary_key_migrations,
)


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0205_sam_mam_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggMPRAwc',
            fields=[
                ('state_id', models.TextField(null=True)),
                ('district_id', models.TextField(null=True)),
                ('block_id', models.TextField(null=True)),
                ('supervisor_id', models.TextField(null=True)),
                ('awc_id', models.TextField(primary_key=True, serialize=False)),
                ('state_is_test', models.SmallIntegerField(null=True)),
                ('district_is_test', models.SmallIntegerField(null=True)),
                ('block_is_test', models.SmallIntegerField(null=True)),
                ('supervisor_is_test', models.SmallIntegerField(null=True)),
                ('awc_is_test', models.SmallIntegerField(null=True)),
                ('month', models.DateField(null=True)),
                ('aggregation_level', models.SmallIntegerField(null=True)),
                ('visitor_icds_sup', models.IntegerField(null=True)),
                ('visitor_anm', models.IntegerField(null=True)),
                ('visitor_health_sup', models.IntegerField(null=True)),
                ('visitor_cdpo', models.IntegerField(null=True)),
                ('visitor_med_officer', models.IntegerField(null=True)),
                ('visitor_dpo', models.IntegerField(null=True)),
                ('visitor_officer_state', models.IntegerField(null=True)),
                ('visitor_officer_central', models.IntegerField(null=True)),
                ('vhnd_done_when_planned', models.IntegerField(null=True)),
                ('vhnd_with_aww_present', models.IntegerField(null=True)),
                ('vhnd_with_icds_sup', models.IntegerField(null=True)),
                ('vhnd_with_asha_present', models.IntegerField(null=True)),
                ('vhnd_with_anm_mpw', models.IntegerField(null=True)),
                ('vhnd_with_health_edu_org', models.IntegerField(null=True)),
                ('vhnd_with_display_tools', models.IntegerField(null=True)),
                ('vhnd_with_thr_distr', models.IntegerField(null=True)),
                ('vhnd_with_child_immu', models.IntegerField(null=True)),
                ('vhnd_with_vit_a_given', models.IntegerField(null=True)),
                ('vhnd_with_anc_today', models.IntegerField(null=True)),
                ('vhnd_with_local_leader', models.IntegerField(null=True)),
                ('vhnd_with_due_list_prep_immunization', models.IntegerField(null=True)),
                ('vhnd_with_due_list_prep_vita_a', models.IntegerField(null=True)),
                ('vhnd_with_due_list_prep_antenatal_checkup', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'agg_mpr_awc'
            },
            bases=(models.Model, custom.icds_reports.models.aggregate.AggregateMixin),
        ),
        migrations.AlterUniqueTogether(
            name='aggmprawc',
            unique_together=set(
                [('month', 'aggregation_level', 'state_id', 'district_id', 'block_id', 'supervisor_id', 'awc_id')]),
        ),
    ]
    operations.extend(get_composite_primary_key_migrations(['aggmprawc']))
