# Generated by Django 2.2.13 on 2020-10-01 15:21

import custom.icds_reports.models.aggregate
from django.db import migrations, models

from custom.icds_reports.const import AGG_PERSON_CASE_TABLE
from custom.icds_reports.utils.migrations import (
    get_composite_primary_key_migrations,
)

class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0212_auto_20200929_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatePersonCase',
            fields=[
                ('state_id', models.TextField(null=True)),
                ('supervisor_id', models.TextField(null=True)),
                ('month', models.DateField(help_text='Will always be YYYY-MM-01')),
                ('awc_id', models.TextField(primary_key=True, serialize=False)),
                ('cases_person', models.IntegerField(null=True)),
                ('cases_person_all', models.IntegerField(null=True)),
                ('cases_person_adolescent_girls_11_14', models.IntegerField(null=True)),
                ('cases_person_adolescent_girls_11_14_all', models.IntegerField(null=True)),
                ('cases_person_adolescent_girls_11_14_all_v2', models.IntegerField(null=True)),
                ('cases_person_adolescent_girls_15_18', models.IntegerField(null=True)),
                ('cases_person_adolescent_girls_15_18_all', models.IntegerField(null=True)),
                ('cases_person_referred', models.IntegerField(null=True)),
                ('num_premature_referral_awcs', models.IntegerField(null=True)),
                ('total_premature_referrals', models.IntegerField(null=True)),
                ('total_premature_reached_facility', models.IntegerField(null=True)),
                ('num_sepsis_referral_awcs', models.IntegerField(null=True)),
                ('total_sepsis_referrals', models.IntegerField(null=True)),
                ('total_sepsis_reached_facility', models.IntegerField(null=True)),
                ('num_diarrhoea_referral_awcs', models.IntegerField(null=True)),
                ('total_diarrhoea_referrals', models.IntegerField(null=True)),
                ('total_diarrhoea_reached_facility', models.IntegerField(null=True)),
                ('num_pneumonia_referral_awcs', models.IntegerField(null=True)),
                ('total_pneumonia_referrals', models.IntegerField(null=True)),
                ('total_pneumonia_reached_facility', models.IntegerField(null=True)),
                ('num_fever_referral_awcs', models.IntegerField(null=True)),
                ('total_fever_referrals', models.IntegerField(null=True)),
                ('total_fever_reached_facility', models.IntegerField(null=True)),
                ('num_severely_underweight_referral_awcs', models.IntegerField(null=True)),
                ('total_severely_underweight_referrals', models.IntegerField(null=True)),
                ('total_severely_underweight_reached_facility', models.IntegerField(null=True)),
                ('num_other_child_referral_awcs', models.IntegerField(null=True)),
                ('total_other_child_referrals', models.IntegerField(null=True)),
                ('total_other_child_reached_facility', models.IntegerField(null=True)),
                ('num_bleeding_referral_awcs', models.IntegerField(null=True)),
                ('total_bleeding_referrals', models.IntegerField(null=True)),
                ('total_bleeding_reached_facility', models.IntegerField(null=True)),
                ('num_convulsions_referral_awcs', models.IntegerField(null=True)),
                ('total_convulsions_referrals', models.IntegerField(null=True)),
                ('total_convulsions_reached_facility', models.IntegerField(null=True)),
                ('num_prolonged_labor_referral_awcs', models.IntegerField(null=True)),
                ('total_prolonged_labor_referrals', models.IntegerField(null=True)),
                ('total_prolonged_labor_reached_facility', models.IntegerField(null=True)),
                ('num_abortion_complications_referral_awcs', models.IntegerField(null=True)),
                ('total_abortion_complications_referrals', models.IntegerField(null=True)),
                ('total_abortion_complications_reached_facility', models.IntegerField(null=True)),
                ('num_fever_discharge_referral_awcs', models.IntegerField(null=True)),
                ('total_fever_discharge_referrals', models.IntegerField(null=True)),
                ('total_fever_discharge_reached_facility', models.IntegerField(null=True)),
                ('num_other_referral_awcs', models.IntegerField(null=True)),
                ('total_other_referrals', models.IntegerField(null=True)),
                ('total_other_reached_facility', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'icds_dashboard_person_cases'
            },
            bases=(models.Model, custom.icds_reports.models.aggregate.AggregateMixin),
        ),
        migrations.AlterUniqueTogether(
            name='aggregatepersoncase',
            unique_together=set([('month', 'state_id','supervisor_id', 'awc_id')]),
        ),
    ]
    operations.extend(get_composite_primary_key_migrations(['aggregatepersoncase']))
    operations += [
        migrations.RunSQL(f"ALTER TABLE {AGG_PERSON_CASE_TABLE} RENAME TO {AGG_PERSON_CASE_TABLE}_old"),
        migrations.RunSQL(f"CREATE TABLE {AGG_PERSON_CASE_TABLE} (LIKE {AGG_PERSON_CASE_TABLE}_old INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING INDEXES) PARTITION BY LIST (month)"),
        migrations.RunSQL(f"SELECT create_distributed_table('{AGG_PERSON_CASE_TABLE}', 'supervisor_id')"),
        migrations.RunSQL(f"DROP TABLE {AGG_PERSON_CASE_TABLE}_old"),
    ]
