# Generated by Django 2.2.13 on 2020-10-27 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0217_rebuild_db_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregatepersoncase',
            name='num_abortion_complications_referral_awcs',
        ),
        migrations.RemoveField(
            model_name='aggregatepersoncase',
            name='num_bleeding_referral_awcs',
        ),
        migrations.RemoveField(
            model_name='aggregatepersoncase',
            name='num_convulsions_referral_awcs',
        ),
        migrations.RemoveField(
            model_name='aggregatepersoncase',
            name='num_diarrhoea_referral_awcs',
        ),
        migrations.RemoveField(
            model_name='aggregatepersoncase',
            name='num_fever_discharge_referral_awcs',
        ),
        migrations.RemoveField(
            model_name='aggregatepersoncase',
            name='num_fever_referral_awcs',
        ),
        migrations.RemoveField(
            model_name='aggregatepersoncase',
            name='num_other_child_referral_awcs',
        ),
        migrations.RemoveField(
            model_name='aggregatepersoncase',
            name='num_other_referral_awcs',
        ),
        migrations.RemoveField(
            model_name='aggregatepersoncase',
            name='num_pneumonia_referral_awcs',
        ),
        migrations.RemoveField(
            model_name='aggregatepersoncase',
            name='num_premature_referral_awcs',
        ),
        migrations.RemoveField(
            model_name='aggregatepersoncase',
            name='num_prolonged_labor_referral_awcs',
        ),
        migrations.RemoveField(
            model_name='aggregatepersoncase',
            name='num_sepsis_referral_awcs',
        ),
        migrations.RemoveField(
            model_name='aggregatepersoncase',
            name='num_severely_underweight_referral_awcs',
        ),
    ]
