# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-11-03
from __future__ import unicode_literals

from django.db import migrations
from custom.icds_reports.utils.migrations import get_view_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0219_removed_unused_cols_from_sdr'),
    ]

    operations = get_view_migrations()
