# Generated by Django 2.2.16 on 2020-12-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0220_add_inactive_aww_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateInactiveAWWView',
            fields=[
                ('awc_id', models.TextField(primary_key=True, serialize=False)),
                ('awc_name', models.TextField(blank=True, null=True)),
                ('awc_site_code', models.TextField(blank=True, db_index=True, null=True)),
                ('supervisor_id', models.TextField(blank=True, null=True)),
                ('supervisor_name', models.TextField(blank=True, null=True)),
                ('block_id', models.TextField(blank=True, null=True)),
                ('block_name', models.TextField(blank=True, null=True)),
                ('district_id', models.TextField(blank=True, null=True)),
                ('district_name', models.TextField(blank=True, null=True)),
                ('state_id', models.TextField(blank=True, null=True)),
                ('state_name', models.TextField(blank=True, null=True)),
                ('first_submission', models.DateField(blank=True, null=True)),
                ('last_submission', models.DateField(blank=True, null=True)),
                ('no_of_days_since_start', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_days_inactive', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inactive_aww_view',
                'managed': False,
            },
        ),
    ]
