
from datetime import date
from django.test import TestCase
from custom.icds_reports.reports.malnutrition_tracker_report import MalnutritionTrackerReport


class TestMTRReport(TestCase):

    def test_mtr_report_data(self):

        excel_data = MalnutritionTrackerReport(
            config={
                'state_id': 'st1',
                'district_id': 'd1',
                'month': date(2017, 5, 1),
                'aggregation_level': 2,
                'domain': 'icds-cas'
            },
            beta=True,
            location='d1'
        ).get_excel_data()

        data = excel_data[0]

        self.assertDictEqual([
            'Malnutrition Tracking Report',
            [['State',
    'District',
    'Block',
    'Sector',
    'AWC Name',
    'AWC Site Code',
    'AWW Phone Number',
    'Child Health Case ID',
    'Name of the Child',
    'Gender',
    'Name of Mother',
    'Mobile Number of Mother',
    'Date of Birth',
    'Age in Months',
    'Height (in cm)',
    'Weight (in kg)',
    'Nutrition status of the child in the month',
    'Growth Chart Zone',
    'Whether referred to NRC/Hospital',
    'Date of referral',
    'Date of admission in NRC/Hospital',
    'Date of Discharge from NRC/Hospital',
    'Home Visit 1',
    'Home Visit 2',
    'Home Visit 3',
    'Home Visit 4',
    'Panchayat 1',
    'Panchayat 2',
    'Panchayat 3',
    'Panchayat 4'],
   ['st1',
                'd1',
                'b1',
                's1',
                'a49',
                'a49',
                'N/A',
                '70b5760f-4258-407f-94de-84f2530d18de',
                'Name 2828',
                'F',
                'रीनाबाई',
                'N/A',
                datetime.date(2016, 10, 14),
                7,
                'N/A',
                Decimal('6.3000000000000000'),
                'Severely Acute Malnutritioned (SAM)',
                'Red',
                'No',
                'N/A',
                'N/A',
                'N/A',
                'N/A',
                'N/A',
                'N/A',
                'N/A',
                'N/A',
                'N/A',
                'N/A',
                'N/A'],
                ['st1',
                    'd1',
                    'b1',
                    's2',
                    'a18',
                    'a18',
                    'N/A',
                    '98bf90f2-ca96-4702-bfb8-1bf94a313ecc',
                    'Name 4403',
                    'M',
                    'प्रकाश बाई पति समरथसिंह',
                    'N/A',
                    datetime.date(2014, 1, 18),
                    40,
                    Decimal('92.0000000000000000'),
                    Decimal('11.0000000000000000'),
                    'Moderately Acute Malnutritioned (MAM)',
                    'Yellow',
                    'No',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A'],
                ['st1',
                    'd1',
                    'b1',
                    's2',
                    'a18',
                    'a18',
                    'N/A',
                    '14be9218-da81-4143-b48c-0710f5d53aaf',
                    'Name 4417',
                    'M',
                    'टमाबाई',
                    'N/A',
                    datetime.date(2013, 12, 13),
                    41,
                    Decimal('92.0000000000000000'),
                    Decimal('11.0000000000000000'),
                    'Moderately Acute Malnutritioned (MAM)',
                    'Yellow',
                    'No',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A'],
                ['st1',
                    'd1',
                    'b1',
                    's2',
                    'a18',
                    'a18',
                    'N/A',
                    'ca040875-2e42-4ce4-acf7-f96695b370f1',
                    'Name 4416',
                    'F',
                    'रामकन्या',
                    'N/A',
                    datetime.date(2012, 6, 3),
                    59,
                    Decimal('95.0000000000000000'),
                    Decimal('12.8000000000000000'),
                    'Normal',
                    'Green',
                    'No',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A'],
                ['st1',
                    'd1',
                    'b1',
                    's2',
                    'a18',
                    'a18',
                    'N/A',
                    'c9ee2435-d7fc-4307-9c18-9d5d83d2a691',
                    'Name 4402',
                    'M',
                    'पोपा बाई',
                    'N/A',
                    datetime.date(2013, 1, 2),
                    52,
                    Decimal('94.0000000000000000'),
                    Decimal('11.0000000000000000'),
                    'Moderately Acute Malnutritioned (MAM)',
                    'Yellow',
                    'No',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A'],
                ['st1',
                    'd1',
                    'b2',
                    's4',
                    'a20',
                    'a20',
                    'N/A',
                    '5c482990-c8ef-45e4-89e9-738d6627b7e0',
                    'Name 1344',
                    'F',
                    'Simabai Prakash',
                    'N/A',
                    datetime.date(2012, 11, 28),
                    54,
                    Decimal('87.0000000000000000'),
                    Decimal('9.7000000000000000'),
                    'Moderately Acute Malnutritioned (MAM)',
                    'Yellow',
                    'Yes',
                    datetime.date(2017, 1, 8),
                    datetime.date(2017, 4, 18),
                    datetime.date(2017, 4, 28),
                    datetime.date(2017, 5, 10),
                    datetime.date(2017, 5, 13),
                    datetime.date(2017, 5, 14),
                    datetime.date(2017, 5, 15),
                    datetime.date(2017, 5, 9),
                    datetime.date(2017, 5, 15),
                    datetime.date(2017, 5, 16),
                    datetime.date(2017, 5, 17)],
                ['st1',
                    'd1',
                    'b2',
                    's4',
                    'a20',
                    'a20',
                    'N/A',
                    '433167bd-d59a-4670-967a-64127e518f1e',
                    'Name 1426',
                    'F',
                    'Lad Kunwar',
                    'N/A',
                    datetime.date(2013, 11, 20),
                    42,
                    Decimal('87.0000000000000000'),
                    Decimal('11.4000000000000000'),
                    'Normal',
                    'Green',
                    'No',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A'],
                ['st1',
                    'd1',
                    'b2',
                    's4',
                    'a20',
                    'a20',
                    'N/A',
                    '24fcbc0a-91d3-4a9c-a651-4d2dd5ddfd42',
                    'Name 1407',
                    'M',
                    'रामकन्या डाबी',
                    'N/A',
                    datetime.date(2012, 5, 4),
                    60,
                    Decimal('100.0000000000000000'),
                    Decimal('13.9000000000000000'),
                    'Normal',
                    'Green',
                    'No',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A'],
                ['st1',
                    'd1',
                    'b2',
                    's4',
                    'a20',
                    'a20',
                    'N/A',
                    'fb1f7ebb-05d1-4a07-86a3-2bcaabe943ae',
                    'Name 1420',
                    'M',
                    'Vimla Bai',
                    'N/A',
                    datetime.date(2014, 1, 3),
                    40,
                    Decimal('88.0000000000000000'),
                    Decimal('11.8000000000000000'),
                    'Normal',
                    'Green',
                    'No',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A'],
                ['st1',
                    'd1',
                    'b2',
                    's4',
                    'a20',
                    'a20',
                    'N/A',
                    '11d6b4ea-b31c-457d-82cc-a5958e4b853c',
                    'Name 1423',
                    'F',
                    'लक्ष्मी बाई मनोहर',
                    'N/A',
                    datetime.date(2013, 7, 27),
                    46,
                    Decimal('83.0000000000000000'),
                    Decimal('9.7000000000000000'),
                    'Normal',
                    'Green',
                    'No',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A']]], data)
